<h2>Meus dados</h2>

<p>
	<a href="/logout" class="btn">Sair</a>
</p>

<div>Nome: <?php echo $usuario->nome_usuario?></div>
<div>Email: <?php echo $usuario->email_usuario?></div>
<div>Status: <?php echo $usuario->status_usuario?></div>
<div>Papel: <?php echo $usuario->papel_usuario?></div>
<div>Data de cadastro: <?php echo $usuario->dta_inc_usuario?></div>
<div>Token: <?php echo $usuario->token_usuario?></div>