<h2>Cadastre-se</h2>

<?php echo $this->form()->openTag($form)?>
<table>
    <tr>
        <td><?php echo $this->formLabel($form->get('nome_usuario'))?></td>
        <td><?php echo $this->formElement($form->get('nome_usuario'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formElementErrors($form->get('nome_usuario'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('email_usuario'))?></td>
        <td><?php echo $this->formElement($form->get('email_usuario'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formElementErrors($form->get('email_usuario'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('confirme_email_usuario'))?></td>
        <td><?php echo $this->formElement($form->get('confirme_email_usuario'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formElementErrors($form->get('confirme_email_usuario'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('senha_usuario'))?></td>
        <td><?php echo $this->formElement($form->get('senha_usuario'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formElementErrors($form->get('senha_usuario'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('confirme_senha'))?></td>
        <td><?php echo $this->formElement($form->get('confirme_senha'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formElementErrors($form->get('confirme_senha'))?></td>
    </tr>
    <tr>
        <td colspan="2"><?php echo $this->formElement($form->get('captcha'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formElementErrors($form->get('captcha'))?></td>
    </tr>
    <tr>
        <td colspan="2"><?php echo $this->formElement($form->get('submit'))?></td>
    </tr>
</table>
<?php echo $this->form()->closeTag($form)?>

<script>
	$('#confirme_email_usuario, #senha_usuario, #confirme_senha').bind('copy paste', function(e) {
		 e.preventDefault();
	});
</script>